server:
  port: 6110

spring:
  datasource:
    username: root
    password: HPyuko12!!
    url: jdbc:mysql://localhost:3306/qingyun?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true

jwt:
  accessTokenExpireTime: P30D
  issuer: qdu.life
  refreshTokenExpireAppTime: P30D
  refreshTokenExpireTime: P30D
  secretKey: HP..yuko12!!>>serv

tencent:
  cos:
    secretId: xxx
    secretKey: xxx12
    region: ap-beijing
    bucketName: qingyun-file-1254798469
    path: https://qingyun-file-1254798469.cos.ap-beijing.myqcloud.com
    prefix: qingyun-file